name: <%= appName %>
cache: <%= randomStr %>
vars:
  home: ${{ env.HOME }}
  db_name: <%= appName %>
  backup_args: --column-statistics=0 -uroot -p98LNaNmPjJbesmEI -h127.0.0.1 --no-data --databases
tasks:
  db_backup:
    - mysqldump ${{ vars.backup_args }} ${{ vars.db_name }} > ./backup/<%= appName %>.sql
